services:
  # Backend API service
  - type: web
    name: digit-classifier-api
    env: python
    region: ohio
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: API_MODEL_PATH
        value: model/mnist_model.keras
      - key: API_ALLOWED_ORIGINS
        value: https://digit-classifier-app.onrender.com
      - key: API_DEBUG_MODE
        value: false
      - key: API_ENABLE_AUGMENTATION
        value: true
      - key: API_MAX_CONCURRENT_PREDICTIONS
        value: 10
      - key: API_MIN_CONTOUR_SIZE
        value: 10
      - key: API_MODEL_VERSION
        value: "1.0"

  # Frontend static site
  - type: web
    name: digit-classifier-app
    env: node
    region: ohio
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: .next/standalone
    staticHeaders:
      - path: /**
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: digit-classifier-api
          type: web
          property: url
